In [1]:
import pandas as pd
import seaborn as sps
import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv('data/retailmax.csv')

In [3]:
features = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

type(scaled_features)

numpy.ndarray

In [5]:
kmeans = KMeans(n_clusters=3, init='k-means++', max_iter=200, n_init=10, random_state=42)

clusters = kmeans.fit_predict(scaled_features)

In [6]:
clusters 
len(clusters)

200

In [7]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [8]:
df['Calif'] = clusters
df

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Calif
0,1,Male,19,15,39,0
1,2,Male,21,15,81,0
2,3,Female,20,16,6,0
3,4,Female,23,16,77,0
4,5,Female,31,17,40,0
...,...,...,...,...,...,...
195,196,Female,35,120,79,1
196,197,Female,45,126,28,2
197,198,Male,32,126,74,1
198,199,Male,32,137,18,1
199,200,Male,30,137,83,1

In [9]:
df['Calif'].value_counts()

Calif
2    91
0    68
1    41
Name: count, dtype: int64

In [ ]:
plt.figure(figsize=(10,6))
plt.figure(figsize=(10,6))
sps.scatterplot(data=df, x='Annual Income (k$)', y='Spending Score (1-100)', hue='Calif', palette='Set1', s=50)
plt.title('Clusters of Customers')
plt.show()
plt.title('Clusters of Customers')
plt.show()

ValueError: Could not interpret value `Anual Income (k$)` for `x`. An entry with this name does not appear in `data`.

In [ ]:
def calcular